package services

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"sync"
	"time"
)

// loginAttempt tracks login attempts for rate limiting
type loginAttempt struct {
	count       int
	lastAttempt time.Time
	lockedUntil time.Time
}

// Rate limiting constants
const (
	maxLoginAttempts     = 5                // Maximum failed attempts before lockout
	loginLockoutDuration = time.Minute      // Lockout duration after max failures
	attemptResetDuration = 15 * time.Minute // Reset attempt count after this duration
)

// Token expiration duration (24 hours)
const tokenExpirationDuration = 24 * time.Hour

// AuthService handles authentication, session tokens, and rate limiting
type AuthService struct {
	// Token management
	sessionToken   string
	tokenMu        sync.RWMutex
	tokenCreatedAt time.Time

	// Rate limiting
	loginAttempts   map[string]*loginAttempt
	loginAttemptsMu sync.RWMutex
}

// NewAuthService creates a new AuthService instance
func NewAuthService() *AuthService {
	return &AuthService{
		loginAttempts: make(map[string]*loginAttempt),
	}
}

// GetSessionToken returns the current session token without generating one
// Returns empty string if no token has been generated yet or if token is expired
// This method is thread-safe
func (s *AuthService) GetSessionToken() string {
	s.tokenMu.RLock()
	defer s.tokenMu.RUnlock()

	// Check if token exists
	if s.sessionToken == "" {
		return ""
	}

	// Check if token is expired
	if !s.tokenCreatedAt.IsZero() && time.Since(s.tokenCreatedAt) > tokenExpirationDuration {
		return "" // Token expired
	}

	return s.sessionToken
}

// GenerateSessionToken creates a cryptographically secure session token
// Returns error on crypto failure instead of panicking
// Implements handlers.TokenGenerator interface
// This method is thread-safe
func (s *AuthService) GenerateSessionToken() (string, error) {
	// Use RLock first to check if token exists and is not expired (fast path)
	s.tokenMu.RLock()
	if s.sessionToken != "" {
		// Check expiration
		if !s.tokenCreatedAt.IsZero() && time.Since(s.tokenCreatedAt) <= tokenExpirationDuration {
			token := s.sessionToken
			s.tokenMu.RUnlock()
			return token, nil
		}
		// Token is expired, need to regenerate
	}
	s.tokenMu.RUnlock()

	// Need to generate - acquire write lock
	s.tokenMu.Lock()
	defer s.tokenMu.Unlock()

	// Double-check after acquiring write lock (token might have been generated by another goroutine)
	if s.sessionToken != "" && !s.tokenCreatedAt.IsZero() && time.Since(s.tokenCreatedAt) <= tokenExpirationDuration {
		return s.sessionToken, nil
	}

	// Generate a new cryptographically secure token
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		slog.Error("Failed to generate secure random token", "error", err)
		return "", fmt.Errorf("generate session token: cryptographic random number generation failed: %w", err)
	}
	s.sessionToken = "iori_" + hex.EncodeToString(b)
	s.tokenCreatedAt = time.Now()

	slog.Info("Generated new session token", "expiresAt", s.tokenCreatedAt.Add(tokenExpirationDuration))

	return s.sessionToken, nil
}

// CheckLoginRateLimit checks if the IP is rate limited
// Returns true if login is allowed, false if rate limited
// Implements handlers.RateLimiter interface
func (s *AuthService) CheckLoginRateLimit(ip string) (bool, time.Duration) {
	s.loginAttemptsMu.RLock()
	attempt, exists := s.loginAttempts[ip]
	s.loginAttemptsMu.RUnlock()

	if !exists {
		return true, 0
	}

	now := time.Now()

	// Check if currently locked out
	if !attempt.lockedUntil.IsZero() && now.Before(attempt.lockedUntil) {
		remaining := attempt.lockedUntil.Sub(now)
		return false, remaining
	}

	// Reset count if enough time has passed since last attempt
	if now.Sub(attempt.lastAttempt) > attemptResetDuration {
		s.loginAttemptsMu.Lock()
		delete(s.loginAttempts, ip)
		s.loginAttemptsMu.Unlock()
		return true, 0
	}

	return true, 0
}

// RecordLoginFailure records a failed login attempt
// Returns the remaining lockout duration if the IP becomes locked
// Implements handlers.RateLimiter interface
func (s *AuthService) RecordLoginFailure(ip string) time.Duration {
	s.loginAttemptsMu.Lock()
	defer s.loginAttemptsMu.Unlock()

	now := time.Now()
	attempt, exists := s.loginAttempts[ip]

	if !exists {
		s.loginAttempts[ip] = &loginAttempt{
			count:       1,
			lastAttempt: now,
		}
		return 0
	}

	// Reset if enough time has passed
	if now.Sub(attempt.lastAttempt) > attemptResetDuration {
		attempt.count = 1
		attempt.lastAttempt = now
		attempt.lockedUntil = time.Time{}
		return 0
	}

	attempt.count++
	attempt.lastAttempt = now

	// Check if should lock out
	if attempt.count >= maxLoginAttempts {
		attempt.lockedUntil = now.Add(loginLockoutDuration)
		slog.Warn("Login rate limit triggered",
			"ip", ip,
			"attempts", attempt.count,
			"lockoutUntil", attempt.lockedUntil,
		)
		return loginLockoutDuration
	}

	return 0
}

// RecordLoginSuccess clears the login attempt counter for an IP
// Implements handlers.RateLimiter interface
func (s *AuthService) RecordLoginSuccess(ip string) {
	s.loginAttemptsMu.Lock()
	defer s.loginAttemptsMu.Unlock()
	delete(s.loginAttempts, ip)
}

// Reset clears all session state (token and login attempts)
// Should be called when the server stops
func (s *AuthService) Reset() {
	// Reset session token
	s.tokenMu.Lock()
	s.sessionToken = ""
	s.tokenCreatedAt = time.Time{}
	s.tokenMu.Unlock()

	// Clear login attempts
	s.loginAttemptsMu.Lock()
	s.loginAttempts = make(map[string]*loginAttempt)
	s.loginAttemptsMu.Unlock()
}
