// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptChange(arg1, arg2) {
  return window['go']['main']['App']['AcceptChange'](arg1, arg2);
}

export function AcceptChanges(arg1, arg2) {
  return window['go']['main']['App']['AcceptChanges'](arg1, arg2);
}

export function AddRecentFolder(arg1) {
  return window['go']['main']['App']['AddRecentFolder'](arg1);
}

export function AttachExistingWorktree(arg1, arg2) {
  return window['go']['main']['App']['AttachExistingWorktree'](arg1, arg2);
}

export function CheckWorktreeHasChanges(arg1) {
  return window['go']['main']['App']['CheckWorktreeHasChanges'](arg1);
}

export function CheckoutBranchForPath(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranchForPath'](arg1, arg2);
}

export function CloneRepository(arg1, arg2) {
  return window['go']['main']['App']['CloneRepository'](arg1, arg2);
}

export function CloseWorktreeSession(arg1) {
  return window['go']['main']['App']['CloseWorktreeSession'](arg1);
}

export function CommitChanges(arg1, arg2) {
  return window['go']['main']['App']['CommitChanges'](arg1, arg2);
}

export function CreateBranchForPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBranchForPath'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateSessionWithGitOption(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSessionWithGitOption'](arg1, arg2, arg3, arg4);
}

export function CreateWorktreeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorktreeSession'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteWorktreeSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorktreeSession'](arg1, arg2);
}

export function FetchChanges(arg1) {
  return window['go']['main']['App']['FetchChanges'](arg1);
}

export function FlushCurrentHistory(arg1) {
  return window['go']['main']['App']['FlushCurrentHistory'](arg1);
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function GetBranchesForPath(arg1) {
  return window['go']['main']['App']['GetBranchesForPath'](arg1);
}

export function GetBranchesForWorktreeCreate(arg1) {
  return window['go']['main']['App']['GetBranchesForWorktreeCreate'](arg1);
}

export function GetChanges(arg1) {
  return window['go']['main']['App']['GetChanges'](arg1);
}

export function GetDefaultServerConfig() {
  return window['go']['main']['App']['GetDefaultServerConfig']();
}

export function GetDirectoryChildren(arg1, arg2) {
  return window['go']['main']['App']['GetDirectoryChildren'](arg1, arg2);
}

export function GetExistingWorktrees(arg1) {
  return window['go']['main']['App']['GetExistingWorktrees'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2);
}

export function GetFileInfo(arg1, arg2) {
  return window['go']['main']['App']['GetFileInfo'](arg1, arg2);
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetGitSyncInfo(arg1) {
  return window['go']['main']['App']['GetGitSyncInfo'](arg1);
}

export function GetHistoryChunk(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetHistoryChunk'](arg1, arg2, arg3, arg4);
}

export function GetHistoryContent(arg1) {
  return window['go']['main']['App']['GetHistoryContent'](arg1);
}

export function GetHistoryContentWithFlush(arg1, arg2) {
  return window['go']['main']['App']['GetHistoryContentWithFlush'](arg1, arg2);
}

export function GetHistoryList() {
  return window['go']['main']['App']['GetHistoryList']();
}

export function GetLocalIPAddresses() {
  return window['go']['main']['App']['GetLocalIPAddresses']();
}

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function GetResourceUsage() {
  return window['go']['main']['App']['GetResourceUsage']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTerminalHistory(arg1, arg2) {
  return window['go']['main']['App']['GetTerminalHistory'](arg1, arg2);
}

export function GetWorktreeSessions(arg1) {
  return window['go']['main']['App']['GetWorktreeSessions'](arg1);
}

export function IsActiveSessionHistory(arg1) {
  return window['go']['main']['App']['IsActiveSessionHistory'](arg1);
}

export function PullChanges(arg1) {
  return window['go']['main']['App']['PullChanges'](arg1);
}

export function PushChanges(arg1) {
  return window['go']['main']['App']['PushChanges'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function ReadFilePartial(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFilePartial'](arg1, arg2, arg3);
}

export function RejectChange(arg1, arg2) {
  return window['go']['main']['App']['RejectChange'](arg1, arg2);
}

export function RejectChanges(arg1, arg2) {
  return window['go']['main']['App']['RejectChanges'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function StartHistoryStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartHistoryStream'](arg1, arg2, arg3, arg4);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopHistoryStream(arg1) {
  return window['go']['main']['App']['StopHistoryStream'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UnstageChange(arg1, arg2) {
  return window['go']['main']['App']['UnstageChange'](arg1, arg2);
}

export function UnstageChanges(arg1, arg2) {
  return window['go']['main']['App']['UnstageChanges'](arg1, arg2);
}

export function UpdateBranchForPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBranchForPath'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2, arg3);
}
