// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {session} from '../models';
import {git} from '../models';
import {server} from '../models';
import {history} from '../models';
import {main} from '../models';

export function AcceptChange(arg1:string,arg2:string):Promise<void>;

export function AcceptChanges(arg1:string,arg2:Array<string>):Promise<services.BatchOperationResult>;

export function AddRecentFolder(arg1:string):Promise<void>;

export function AttachExistingWorktree(arg1:string,arg2:string):Promise<session.SessionInfo>;

export function CheckWorktreeHasChanges(arg1:string):Promise<boolean>;

export function CheckoutBranchForPath(arg1:string,arg2:string):Promise<void>;

export function CloneRepository(arg1:string,arg2:string):Promise<string>;

export function CloseWorktreeSession(arg1:string):Promise<void>;

export function CommitChanges(arg1:string,arg2:string):Promise<string>;

export function CreateBranchForPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<session.SessionInfo>;

export function CreateSessionWithGitOption(arg1:string,arg2:string,arg3:string,arg4:string):Promise<session.SessionInfo>;

export function CreateWorktreeSession(arg1:string,arg2:string,arg3:string):Promise<session.SessionInfo>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteWorktreeSession(arg1:string,arg2:boolean):Promise<void>;

export function FetchChanges(arg1:string):Promise<void>;

export function FlushCurrentHistory(arg1:string):Promise<string>;

export function GenerateQRCode(arg1:string):Promise<string>;

export function GetBranchesForPath(arg1:string):Promise<Array<services.BranchInfo>>;

export function GetBranchesForWorktreeCreate(arg1:string):Promise<Array<services.BranchInfo>>;

export function GetChanges(arg1:string):Promise<Array<git.FileChange>>;

export function GetDefaultServerConfig():Promise<server.Config>;

export function GetDirectoryChildren(arg1:string,arg2:string):Promise<Array<session.FileNode>>;

export function GetExistingWorktrees(arg1:string):Promise<Array<services.WorktreeInfo>>;

export function GetFileDiff(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetFileInfo(arg1:string,arg2:string):Promise<session.FileMetadata>;

export function GetFileTree(arg1:string):Promise<Array<session.FileNode>>;

export function GetGitSyncInfo(arg1:string):Promise<services.GitSyncInfo>;

export function GetHistoryChunk(arg1:string,arg2:number,arg3:number,arg4:string):Promise<history.HistoryChunk>;

export function GetHistoryContent(arg1:string):Promise<history.TerminalHistory>;

export function GetHistoryContentWithFlush(arg1:string,arg2:string):Promise<history.TerminalHistory>;

export function GetHistoryList():Promise<Array<history.HistoryInfo>>;

export function GetLocalIPAddresses():Promise<Array<string>>;

export function GetRecentFolders():Promise<Array<main.RecentFolder>>;

export function GetResourceUsage():Promise<main.ResourceUsage>;

export function GetServerStatus():Promise<server.ServerStatus>;

export function GetSessions():Promise<Array<session.SessionInfo>>;

export function GetTerminalHistory(arg1:string,arg2:string):Promise<string>;

export function GetWorktreeSessions(arg1:string):Promise<Array<session.SessionInfo>>;

export function IsActiveSessionHistory(arg1:string):Promise<services.ActiveSessionInfo>;

export function PullChanges(arg1:string):Promise<void>;

export function PushChanges(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ReadFilePartial(arg1:string,arg2:string,arg3:number):Promise<services.PartialFileContent>;

export function RejectChange(arg1:string,arg2:string):Promise<void>;

export function RejectChanges(arg1:string,arg2:Array<string>):Promise<services.BatchOperationResult>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetActiveSession(arg1:string):Promise<void>;

export function StartHistoryStream(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function StartServer(arg1:server.Config):Promise<void>;

export function StopHistoryStream(arg1:string):Promise<void>;

export function StopServer():Promise<void>;

export function UnstageChange(arg1:string,arg2:string):Promise<void>;

export function UnstageChanges(arg1:string,arg2:Array<string>):Promise<services.BatchOperationResult>;

export function UpdateBranchForPath(arg1:string,arg2:string,arg3:boolean):Promise<services.PullResult>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string,arg3:string):Promise<void>;
